version: '3'
services:
  db:
    image: postgres:14
    container_name: myapp-name-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: myapp-name-web
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/usr/src/app/:cached
      - bundle:/usr/local/bundle
      - rails_cache:/usr/src/app/tmp/cache
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: myapp-name-worker
    command: bundle exec sidekiq -e development -c 3
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:latest
    container_name: myapp-name-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  bundle:
  db_data:
  node_modules:
  rails_cache:
  redis:
